# coding: utf-8

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from space_tycoon_client.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    NoneClass,
    BoolClass,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class StaticData(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    
    
    class ship_classes(
        DictSchema
    ):
        
        
        class _additional_properties(
            DictSchema
        ):
            name = StrSchema
            shipyard = BoolSchema
            speed = Float64Schema
            cargo_capacity = Int64Schema
            locals()["cargo-capacity"] = cargo_capacity
            del locals()['cargo_capacity']
            life = Int64Schema
            damage = Int64Schema
        
        
            def __new__(
                cls,
                *args: typing.Union[dict, frozendict, ],
                name: typing.Union[name, Unset] = unset,
                shipyard: typing.Union[shipyard, Unset] = unset,
                speed: typing.Union[speed, Unset] = unset,
                life: typing.Union[life, Unset] = unset,
                damage: typing.Union[damage, Unset] = unset,
                _configuration: typing.Optional[Configuration] = None,
                **kwargs: typing.Type[Schema],
            ) -> '_additional_properties':
                return super().__new__(
                    cls,
                    *args,
                    name=name,
                    shipyard=shipyard,
                    speed=speed,
                    life=life,
                    damage=damage,
                    _configuration=_configuration,
                    **kwargs,
                )
    
    
        def __new__(
            cls,
            *args: typing.Union[dict, frozendict, ],
            _configuration: typing.Optional[Configuration] = None,
            **kwargs: typing.Type[Schema],
        ) -> 'ship_classes':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
                **kwargs,
            )
    locals()["ship-classes"] = ship_classes
    del locals()['ship_classes']
    
    
    class resource_names(
        DictSchema
    ):
        _additional_properties = StrSchema
    
    
        def __new__(
            cls,
            *args: typing.Union[dict, frozendict, ],
            _configuration: typing.Optional[Configuration] = None,
            **kwargs: typing.Type[Schema],
        ) -> 'resource_names':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
                **kwargs,
            )
    locals()["resource-names"] = resource_names
    del locals()['resource_names']


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'StaticData':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
            **kwargs,
        )
