/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type PlanetResource struct {

	BuyPrice float64 `json:"buy-price,omitempty"`

	SellPrice float64 `json:"sell-price,omitempty"`
}

// AssertPlanetResourceRequired checks if the required fields are not zero-ed
func AssertPlanetResourceRequired(obj PlanetResource) error {
	return nil
}

// AssertRecursePlanetResourceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PlanetResource (e.g. [][]PlanetResource), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePlanetResourceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPlanetResource, ok := obj.(PlanetResource)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPlanetResourceRequired(aPlanetResource)
	})
}
