/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type HistoryIdentifier struct {

	Tick int64 `json:"tick"`

	Season int64 `json:"season"`
}

// AssertHistoryIdentifierRequired checks if the required fields are not zero-ed
func AssertHistoryIdentifierRequired(obj HistoryIdentifier) error {
	elements := map[string]interface{}{
		"tick": obj.Tick,
		"season": obj.Season,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseHistoryIdentifierRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of HistoryIdentifier (e.g. [][]HistoryIdentifier), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseHistoryIdentifierRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aHistoryIdentifier, ok := obj.(HistoryIdentifier)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertHistoryIdentifierRequired(aHistoryIdentifier)
	})
}
