/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type TradingResourceAllOf struct {

	BuyPrice float64 `json:"buyPrice,omitempty"`

	SellPrice float64 `json:"sellPrice,omitempty"`
}

// AssertTradingResourceAllOfRequired checks if the required fields are not zero-ed
func AssertTradingResourceAllOfRequired(obj TradingResourceAllOf) error {
	return nil
}

// AssertRecurseTradingResourceAllOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TradingResourceAllOf (e.g. [][]TradingResourceAllOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTradingResourceAllOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTradingResourceAllOf, ok := obj.(TradingResourceAllOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTradingResourceAllOfRequired(aTradingResourceAllOf)
	})
}
