/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type Profiling struct {

	Tick int64 `json:"tick,omitempty"`

	Movement int64 `json:"movement,omitempty"`

	Attacks int64 `json:"attacks,omitempty"`

	Trades int64 `json:"trades,omitempty"`

	Recipes int64 `json:"recipes,omitempty"`

	Prices int64 `json:"prices,omitempty"`

	Constructions int64 `json:"constructions,omitempty"`

	Report int64 `json:"report,omitempty"`

	Total int64 `json:"total,omitempty"`

	Overall int64 `json:"overall,omitempty"`

	At int64 `json:"at,omitempty"`
}

// AssertProfilingRequired checks if the required fields are not zero-ed
func AssertProfilingRequired(obj Profiling) error {
	return nil
}

// AssertRecurseProfilingRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Profiling (e.g. [][]Profiling), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseProfilingRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aProfiling, ok := obj.(Profiling)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertProfilingRequired(aProfiling)
	})
}
