/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type AttackCommand struct {
	Command

	Target int64 `json:"target"`
}

// AssertAttackCommandRequired checks if the required fields are not zero-ed
func AssertAttackCommandRequired(obj AttackCommand) error {
	elements := map[string]interface{}{
		"target": obj.Target,
		"class": obj.Class,
		"name": obj.Name,
		"resource": obj.Resource,
		"amount": obj.Amount,
		"where": obj.Where,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCommandRequired(obj.Command); err != nil {
		return err
	}

	return nil
}

// AssertRecurseAttackCommandRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AttackCommand (e.g. [][]AttackCommand), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAttackCommandRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAttackCommand, ok := obj.(AttackCommand)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAttackCommandRequired(aAttackCommand)
	})
}
