/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type RenameCommandAllOf struct {

	Name string `json:"name"`
}

// AssertRenameCommandAllOfRequired checks if the required fields are not zero-ed
func AssertRenameCommandAllOfRequired(obj RenameCommandAllOf) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseRenameCommandAllOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of RenameCommandAllOf (e.g. [][]RenameCommandAllOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseRenameCommandAllOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aRenameCommandAllOf, ok := obj.(RenameCommandAllOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertRenameCommandAllOfRequired(aRenameCommandAllOf)
	})
}
