/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type PlayersValue struct {

	Name string `json:"name"`

	Color []int32 `json:"color"`

	NetWorth NetWorth `json:"net-worth"`
}

// AssertPlayersValueRequired checks if the required fields are not zero-ed
func AssertPlayersValueRequired(obj PlayersValue) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"color": obj.Color,
		"net-worth": obj.NetWorth,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNetWorthRequired(obj.NetWorth); err != nil {
		return err
	}
	return nil
}

// AssertRecursePlayersValueRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PlayersValue (e.g. [][]PlayersValue), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePlayersValueRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPlayersValue, ok := obj.(PlayersValue)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPlayersValueRequired(aPlayersValue)
	})
}
