/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type PriceValue struct {

	Tick int64 `json:"tick,omitempty"`

	Buyer int64 `json:"buyer,omitempty"`

	Seller int64 `json:"seller,omitempty"`

	Resource int64 `json:"resource,omitempty"`

	Amount int64 `json:"amount,omitempty"`

	Price int64 `json:"price,omitempty"`
}

// AssertPriceValueRequired checks if the required fields are not zero-ed
func AssertPriceValueRequired(obj PriceValue) error {
	return nil
}

// AssertRecursePriceValueRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PriceValue (e.g. [][]PriceValue), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePriceValueRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPriceValue, ok := obj.(PriceValue)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPriceValueRequired(aPriceValue)
	})
}
