/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type PlayerId struct {

	Id string `json:"id,omitempty"`
}

// AssertPlayerIdRequired checks if the required fields are not zero-ed
func AssertPlayerIdRequired(obj PlayerId) error {
	return nil
}

// AssertRecursePlayerIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PlayerId (e.g. [][]PlayerId), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePlayerIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPlayerId, ok := obj.(PlayerId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPlayerIdRequired(aPlayerId)
	})
}
