/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type ConstructCommandAllOf struct {
	ShipClass int64 `json:"ship-class"`
}

// AssertConstructCommandAllOfRequired checks if the required fields are not zero-ed
func AssertConstructCommandAllOfRequired(obj ConstructCommandAllOf) error {
	elements := map[string]interface{}{
		"ship-class": obj.ShipClass,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseConstructCommandAllOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ConstructCommandAllOf (e.g. [][]ConstructCommandAllOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseConstructCommandAllOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aConstructCommandAllOf, ok := obj.(ConstructCommandAllOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertConstructCommandAllOfRequired(aConstructCommandAllOf)
	})
}
