/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type AggregatedReports struct {

	// Profiling information about the game. Used by the visualization website.
	Profiling []Profiling `json:"profiling,omitempty"`

	// Prices are average across all planets.
	Prices map[string]map[string]int64 `json:"prices,omitempty"`

	Scores map[string]ScoreValue `json:"scores,omitempty"`
}

// AssertAggregatedReportsRequired checks if the required fields are not zero-ed
func AssertAggregatedReportsRequired(obj AggregatedReports) error {
	for _, el := range obj.Profiling {
		if err := AssertProfilingRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseAggregatedReportsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AggregatedReports (e.g. [][]AggregatedReports), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAggregatedReportsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAggregatedReports, ok := obj.(AggregatedReports)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAggregatedReportsRequired(aAggregatedReports)
	})
}
