/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type Credentials struct {

	Username string `json:"username"`

	Password string `json:"password"`
}

// AssertCredentialsRequired checks if the required fields are not zero-ed
func AssertCredentialsRequired(obj Credentials) error {
	elements := map[string]interface{}{
		"username": obj.Username,
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseCredentialsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Credentials (e.g. [][]Credentials), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCredentialsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCredentials, ok := obj.(Credentials)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCredentialsRequired(aCredentials)
	})
}
