/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type ShipsValue struct {

	ShipClass int64 `json:"ship-class,omitempty"`

	Life int64 `json:"life,omitempty"`

	Name string `json:"name,omitempty"`

	Player int64 `json:"player,omitempty"`

	Position []int64 `json:"position,omitempty"`

	PrevPosition []int64 `json:"prev-position,omitempty"`

	Resources map[string]Resource `json:"resources,omitempty"`

	Command Command `json:"command,omitempty"`
}

// AssertShipsValueRequired checks if the required fields are not zero-ed
func AssertShipsValueRequired(obj ShipsValue) error {
	if err := AssertCommandRequired(obj.Command); err != nil {
		return err
	}
	return nil
}

// AssertRecurseShipsValueRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ShipsValue (e.g. [][]ShipsValue), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseShipsValueRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aShipsValue, ok := obj.(ShipsValue)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertShipsValueRequired(aShipsValue)
	})
}
