/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type EndTurn struct {

	Tick int64 `json:"tick"`

	Season int64 `json:"season"`
}

// AssertEndTurnRequired checks if the required fields are not zero-ed
func AssertEndTurnRequired(obj EndTurn) error {
	elements := map[string]interface{}{
		"tick": obj.Tick,
		"season": obj.Season,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseEndTurnRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of EndTurn (e.g. [][]EndTurn), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseEndTurnRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aEndTurn, ok := obj.(EndTurn)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertEndTurnRequired(aEndTurn)
	})
}
