/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type Stats struct {

	Money int64 `json:"money,omitempty"`

	Resources int64 `json:"resources,omitempty"`

	Ships int64 `json:"ships,omitempty"`

	Total int64 `json:"total,omitempty"`
}

// AssertStatsRequired checks if the required fields are not zero-ed
func AssertStatsRequired(obj Stats) error {
	return nil
}

// AssertRecurseStatsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Stats (e.g. [][]Stats), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseStatsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aStats, ok := obj.(Stats)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertStatsRequired(aStats)
	})
}
