/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type Trade struct {

	Tick int64 `json:"tick,omitempty"`

	Buyer int64 `json:"buyer,omitempty"`

	Seller int64 `json:"seller,omitempty"`

	Resource int64 `json:"resource,omitempty"`

	Amount int64 `json:"amount,omitempty"`

	Price int64 `json:"price,omitempty"`
}

// AssertTradeRequired checks if the required fields are not zero-ed
func AssertTradeRequired(obj Trade) error {
	return nil
}

// AssertRecurseTradeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Trade (e.g. [][]Trade), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTradeRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTrade, ok := obj.(Trade)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTradeRequired(aTrade)
	})
}
