/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type PlayersValue struct {

	Name string `json:"name,omitempty"`

	Color []int32 `json:"color,omitempty"`

	Stats Stats `json:"stats,omitempty"`
}

// AssertPlayersValueRequired checks if the required fields are not zero-ed
func AssertPlayersValueRequired(obj PlayersValue) error {
	if err := AssertStatsRequired(obj.Stats); err != nil {
		return err
	}
	return nil
}

// AssertRecursePlayersValueRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PlayersValue (e.g. [][]PlayersValue), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePlayersValueRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPlayersValue, ok := obj.(PlayersValue)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPlayersValueRequired(aPlayersValue)
	})
}
