/*
 * Space Tycoon
 *
 * Space Tycoon server.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stycoon

type LoginPost200Response struct {

	PlayerId int64 `json:"player-id,omitempty"`
}

// AssertLoginPost200ResponseRequired checks if the required fields are not zero-ed
func AssertLoginPost200ResponseRequired(obj LoginPost200Response) error {
	return nil
}

// AssertRecurseLoginPost200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of LoginPost200Response (e.g. [][]LoginPost200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseLoginPost200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aLoginPost200Response, ok := obj.(LoginPost200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertLoginPost200ResponseRequired(aLoginPost200Response)
	})
}
