# coding: utf-8

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import space_tycoon_client
from space_tycoon_client.model.trading_resources import TradingResources
from space_tycoon_client import configuration


class TestTradingResources(unittest.TestCase):
    """TradingResources unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
