# coding: utf-8

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Command(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'target': 'str',
        'destination': 'Destination',
        'resource': 'str',
        'amount': 'int',
        'ship_class': 'str',
        'name': 'str'
    }

    attribute_map = {
        'type': 'type',
        'target': 'target',
        'destination': 'destination',
        'resource': 'resource',
        'amount': 'amount',
        'ship_class': 'shipClass',
        'name': 'name'
    }

    def __init__(self, type=None, target=None, destination=None, resource=None, amount=None, ship_class=None, name=None):  # noqa: E501
        """Command - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._target = None
        self._destination = None
        self._resource = None
        self._amount = None
        self._ship_class = None
        self._name = None
        self.discriminator = None
        self.type = type
        if target is not None:
            self.target = target
        if destination is not None:
            self.destination = destination
        if resource is not None:
            self.resource = resource
        if amount is not None:
            self.amount = amount
        if ship_class is not None:
            self.ship_class = ship_class
        if name is not None:
            self.name = name

    @property
    def type(self):
        """Gets the type of this Command.  # noqa: E501


        :return: The type of this Command.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Command.


        :param type: The type of this Command.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def target(self):
        """Gets the target of this Command.  # noqa: E501


        :return: The target of this Command.  # noqa: E501
        :rtype: str
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this Command.


        :param target: The target of this Command.  # noqa: E501
        :type: str
        """

        self._target = target

    @property
    def destination(self):
        """Gets the destination of this Command.  # noqa: E501


        :return: The destination of this Command.  # noqa: E501
        :rtype: Destination
        """
        return self._destination

    @destination.setter
    def destination(self, destination):
        """Sets the destination of this Command.


        :param destination: The destination of this Command.  # noqa: E501
        :type: Destination
        """

        self._destination = destination

    @property
    def resource(self):
        """Gets the resource of this Command.  # noqa: E501


        :return: The resource of this Command.  # noqa: E501
        :rtype: str
        """
        return self._resource

    @resource.setter
    def resource(self, resource):
        """Sets the resource of this Command.


        :param resource: The resource of this Command.  # noqa: E501
        :type: str
        """

        self._resource = resource

    @property
    def amount(self):
        """Gets the amount of this Command.  # noqa: E501


        :return: The amount of this Command.  # noqa: E501
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this Command.


        :param amount: The amount of this Command.  # noqa: E501
        :type: int
        """

        self._amount = amount

    @property
    def ship_class(self):
        """Gets the ship_class of this Command.  # noqa: E501


        :return: The ship_class of this Command.  # noqa: E501
        :rtype: str
        """
        return self._ship_class

    @ship_class.setter
    def ship_class(self, ship_class):
        """Sets the ship_class of this Command.


        :param ship_class: The ship_class of this Command.  # noqa: E501
        :type: str
        """

        self._ship_class = ship_class

    @property
    def name(self):
        """Gets the name of this Command.  # noqa: E501


        :return: The name of this Command.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Command.


        :param name: The name of this Command.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Command, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Command):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
