# coding: utf-8

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConstructCommand(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ship_class': 'str',
        'type': 'str'
    }

    attribute_map = {
        'ship_class': 'shipClass',
        'type': 'type'
    }

    def __init__(self, ship_class=None, type='construct'):  # noqa: E501
        """ConstructCommand - a model defined in Swagger"""  # noqa: E501
        self._ship_class = None
        self._type = None
        self.discriminator = None
        self.ship_class = ship_class
        if type is not None:
            self.type = type

    @property
    def ship_class(self):
        """Gets the ship_class of this ConstructCommand.  # noqa: E501


        :return: The ship_class of this ConstructCommand.  # noqa: E501
        :rtype: str
        """
        return self._ship_class

    @ship_class.setter
    def ship_class(self, ship_class):
        """Sets the ship_class of this ConstructCommand.


        :param ship_class: The ship_class of this ConstructCommand.  # noqa: E501
        :type: str
        """
        if ship_class is None:
            raise ValueError("Invalid value for `ship_class`, must not be `None`")  # noqa: E501

        self._ship_class = ship_class

    @property
    def type(self):
        """Gets the type of this ConstructCommand.  # noqa: E501


        :return: The type of this ConstructCommand.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ConstructCommand.


        :param type: The type of this ConstructCommand.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConstructCommand, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConstructCommand):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
