# coding: utf-8

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataReports(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'combat': 'list[Combat]',
        'trade': 'list[Trade]'
    }

    attribute_map = {
        'combat': 'combat',
        'trade': 'trade'
    }

    def __init__(self, combat=None, trade=None):  # noqa: E501
        """DataReports - a model defined in Swagger"""  # noqa: E501
        self._combat = None
        self._trade = None
        self.discriminator = None
        if combat is not None:
            self.combat = combat
        if trade is not None:
            self.trade = trade

    @property
    def combat(self):
        """Gets the combat of this DataReports.  # noqa: E501


        :return: The combat of this DataReports.  # noqa: E501
        :rtype: list[Combat]
        """
        return self._combat

    @combat.setter
    def combat(self, combat):
        """Sets the combat of this DataReports.


        :param combat: The combat of this DataReports.  # noqa: E501
        :type: list[Combat]
        """

        self._combat = combat

    @property
    def trade(self):
        """Gets the trade of this DataReports.  # noqa: E501


        :return: The trade of this DataReports.  # noqa: E501
        :rtype: list[Trade]
        """
        return self._trade

    @trade.setter
    def trade(self, trade):
        """Sets the trade of this DataReports.


        :param trade: The trade of this DataReports.  # noqa: E501
        :type: list[Trade]
        """

        self._trade = trade

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataReports, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataReports):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
