# coding: utf-8

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Reports(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'combat': 'list[Combat]',
        'profiling': 'list[Profiling]',
        'prices': 'Price',
        'scores': 'Score',
        'trade': 'list[Trade]'
    }

    attribute_map = {
        'combat': 'combat',
        'profiling': 'profiling',
        'prices': 'prices',
        'scores': 'scores',
        'trade': 'trade'
    }

    def __init__(self, combat=None, profiling=None, prices=None, scores=None, trade=None):  # noqa: E501
        """Reports - a model defined in Swagger"""  # noqa: E501
        self._combat = None
        self._profiling = None
        self._prices = None
        self._scores = None
        self._trade = None
        self.discriminator = None
        if combat is not None:
            self.combat = combat
        if profiling is not None:
            self.profiling = profiling
        if prices is not None:
            self.prices = prices
        if scores is not None:
            self.scores = scores
        if trade is not None:
            self.trade = trade

    @property
    def combat(self):
        """Gets the combat of this Reports.  # noqa: E501


        :return: The combat of this Reports.  # noqa: E501
        :rtype: list[Combat]
        """
        return self._combat

    @combat.setter
    def combat(self, combat):
        """Sets the combat of this Reports.


        :param combat: The combat of this Reports.  # noqa: E501
        :type: list[Combat]
        """

        self._combat = combat

    @property
    def profiling(self):
        """Gets the profiling of this Reports.  # noqa: E501

        Profiling information about the game. Used by the visualization website.  # noqa: E501

        :return: The profiling of this Reports.  # noqa: E501
        :rtype: list[Profiling]
        """
        return self._profiling

    @profiling.setter
    def profiling(self, profiling):
        """Sets the profiling of this Reports.

        Profiling information about the game. Used by the visualization website.  # noqa: E501

        :param profiling: The profiling of this Reports.  # noqa: E501
        :type: list[Profiling]
        """

        self._profiling = profiling

    @property
    def prices(self):
        """Gets the prices of this Reports.  # noqa: E501


        :return: The prices of this Reports.  # noqa: E501
        :rtype: Price
        """
        return self._prices

    @prices.setter
    def prices(self, prices):
        """Sets the prices of this Reports.


        :param prices: The prices of this Reports.  # noqa: E501
        :type: Price
        """

        self._prices = prices

    @property
    def scores(self):
        """Gets the scores of this Reports.  # noqa: E501


        :return: The scores of this Reports.  # noqa: E501
        :rtype: Score
        """
        return self._scores

    @scores.setter
    def scores(self, scores):
        """Sets the scores of this Reports.


        :param scores: The scores of this Reports.  # noqa: E501
        :type: Score
        """

        self._scores = scores

    @property
    def trade(self):
        """Gets the trade of this Reports.  # noqa: E501


        :return: The trade of this Reports.  # noqa: E501
        :rtype: list[Trade]
        """
        return self._trade

    @trade.setter
    def trade(self, trade):
        """Sets the trade of this Reports.


        :param trade: The trade of this Reports.  # noqa: E501
        :type: list[Trade]
        """

        self._trade = trade

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Reports, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Reports):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
