# coding: utf-8

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StaticData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ship_classes': 'dict(str, ShipClass)',
        'resource_names': 'dict(str, str)'
    }

    attribute_map = {
        'ship_classes': 'shipClasses',
        'resource_names': 'resourceNames'
    }

    def __init__(self, ship_classes=None, resource_names=None):  # noqa: E501
        """StaticData - a model defined in Swagger"""  # noqa: E501
        self._ship_classes = None
        self._resource_names = None
        self.discriminator = None
        if ship_classes is not None:
            self.ship_classes = ship_classes
        if resource_names is not None:
            self.resource_names = resource_names

    @property
    def ship_classes(self):
        """Gets the ship_classes of this StaticData.  # noqa: E501


        :return: The ship_classes of this StaticData.  # noqa: E501
        :rtype: dict(str, ShipClass)
        """
        return self._ship_classes

    @ship_classes.setter
    def ship_classes(self, ship_classes):
        """Sets the ship_classes of this StaticData.


        :param ship_classes: The ship_classes of this StaticData.  # noqa: E501
        :type: dict(str, ShipClass)
        """

        self._ship_classes = ship_classes

    @property
    def resource_names(self):
        """Gets the resource_names of this StaticData.  # noqa: E501


        :return: The resource_names of this StaticData.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._resource_names

    @resource_names.setter
    def resource_names(self, resource_names):
        """Sets the resource_names of this StaticData.


        :param resource_names: The resource_names of this StaticData.  # noqa: E501
        :type: dict(str, str)
        """

        self._resource_names = resource_names

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StaticData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StaticData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
