# coding: utf-8

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Wreck(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ship_class': 'str',
        'name': 'str',
        'player': 'str',
        'kill_tick': 'int',
        'position': 'Coordinates'
    }

    attribute_map = {
        'ship_class': 'shipClass',
        'name': 'name',
        'player': 'player',
        'kill_tick': 'killTick',
        'position': 'position'
    }

    def __init__(self, ship_class=None, name=None, player=None, kill_tick=None, position=None):  # noqa: E501
        """Wreck - a model defined in Swagger"""  # noqa: E501
        self._ship_class = None
        self._name = None
        self._player = None
        self._kill_tick = None
        self._position = None
        self.discriminator = None
        self.ship_class = ship_class
        self.name = name
        self.player = player
        self.kill_tick = kill_tick
        self.position = position

    @property
    def ship_class(self):
        """Gets the ship_class of this Wreck.  # noqa: E501


        :return: The ship_class of this Wreck.  # noqa: E501
        :rtype: str
        """
        return self._ship_class

    @ship_class.setter
    def ship_class(self, ship_class):
        """Sets the ship_class of this Wreck.


        :param ship_class: The ship_class of this Wreck.  # noqa: E501
        :type: str
        """
        if ship_class is None:
            raise ValueError("Invalid value for `ship_class`, must not be `None`")  # noqa: E501

        self._ship_class = ship_class

    @property
    def name(self):
        """Gets the name of this Wreck.  # noqa: E501


        :return: The name of this Wreck.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Wreck.


        :param name: The name of this Wreck.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def player(self):
        """Gets the player of this Wreck.  # noqa: E501


        :return: The player of this Wreck.  # noqa: E501
        :rtype: str
        """
        return self._player

    @player.setter
    def player(self, player):
        """Sets the player of this Wreck.


        :param player: The player of this Wreck.  # noqa: E501
        :type: str
        """
        if player is None:
            raise ValueError("Invalid value for `player`, must not be `None`")  # noqa: E501

        self._player = player

    @property
    def kill_tick(self):
        """Gets the kill_tick of this Wreck.  # noqa: E501


        :return: The kill_tick of this Wreck.  # noqa: E501
        :rtype: int
        """
        return self._kill_tick

    @kill_tick.setter
    def kill_tick(self, kill_tick):
        """Sets the kill_tick of this Wreck.


        :param kill_tick: The kill_tick of this Wreck.  # noqa: E501
        :type: int
        """
        if kill_tick is None:
            raise ValueError("Invalid value for `kill_tick`, must not be `None`")  # noqa: E501

        self._kill_tick = kill_tick

    @property
    def position(self):
        """Gets the position of this Wreck.  # noqa: E501


        :return: The position of this Wreck.  # noqa: E501
        :rtype: Coordinates
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this Wreck.


        :param position: The position of this Wreck.  # noqa: E501
        :type: Coordinates
        """
        if position is None:
            raise ValueError("Invalid value for `position`, must not be `None`")  # noqa: E501

        self._position = position

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Wreck, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Wreck):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
