# coding: utf-8

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from space_tycoon_client.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    NoneClass,
    BoolClass,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class Reports(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    
    
    class combat(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['Combat']:
            return Combat
    
    
    class profiling(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['Profiling']:
            return Profiling
    
    
    class prices(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['Price']:
            return Price
    
    
    class scores(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['Score']:
            return Score
    
    
    class trade(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['Trade']:
            return Trade


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        combat: typing.Union[combat, Unset] = unset,
        profiling: typing.Union[profiling, Unset] = unset,
        prices: typing.Union[prices, Unset] = unset,
        scores: typing.Union[scores, Unset] = unset,
        trade: typing.Union[trade, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'Reports':
        return super().__new__(
            cls,
            *args,
            combat=combat,
            profiling=profiling,
            prices=prices,
            scores=scores,
            trade=trade,
            _configuration=_configuration,
            **kwargs,
        )

from space_tycoon_client.model.combat import Combat
from space_tycoon_client.model.price import Price
from space_tycoon_client.model.profiling import Profiling
from space_tycoon_client.model.score import Score
from space_tycoon_client.model.trade import Trade
