# coding: utf-8

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from space_tycoon_client.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    NoneClass,
    BoolClass,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class Trade(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    tick = Int64Schema
    buyer = Int64Schema
    seller = Int64Schema
    resource = Int64Schema
    amount = Int64Schema
    price = Int64Schema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        tick: typing.Union[tick, Unset] = unset,
        buyer: typing.Union[buyer, Unset] = unset,
        seller: typing.Union[seller, Unset] = unset,
        resource: typing.Union[resource, Unset] = unset,
        amount: typing.Union[amount, Unset] = unset,
        price: typing.Union[price, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'Trade':
        return super().__new__(
            cls,
            *args,
            tick=tick,
            buyer=buyer,
            seller=seller,
            resource=resource,
            amount=amount,
            price=price,
            _configuration=_configuration,
            **kwargs,
        )
