"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import space_tycoon_client
from space_tycoon_client.model.attack_command_all_of import AttackCommandAllOf
from space_tycoon_client.model.command import Command
globals()['AttackCommandAllOf'] = AttackCommandAllOf
globals()['Command'] = Command
from space_tycoon_client.model.attack_command import AttackCommand


class TestAttackCommand(unittest.TestCase):
    """AttackCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttackCommand(self):
        """Test AttackCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttackCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
