"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import space_tycoon_client
from space_tycoon_client.model.planets_value import PlanetsValue
globals()['PlanetsValue'] = PlanetsValue
from space_tycoon_client.model.planets import Planets


class TestPlanets(unittest.TestCase):
    """Planets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlanets(self):
        """Test Planets"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Planets()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
