"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import space_tycoon_client
from space_tycoon_client.model.destination import Destination
globals()['Destination'] = Destination
from space_tycoon_client.model.move_command_all_of import MoveCommandAllOf


class TestMoveCommandAllOf(unittest.TestCase):
    """MoveCommandAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMoveCommandAllOf(self):
        """Test MoveCommandAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MoveCommandAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
