"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import space_tycoon_client
from space_tycoon_client.api.end_turn_api import EndTurnApi  # noqa: E501


class TestEndTurnApi(unittest.TestCase):
    """EndTurnApi unit test stubs"""

    def setUp(self):
        self.api = EndTurnApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_end_turn_post(self):
        """Test case for end_turn_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
