"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import space_tycoon_client
from space_tycoon_client.model.command import Command
from space_tycoon_client.model.coordinates import Coordinates
from space_tycoon_client.model.resources import Resources
globals()['Command'] = Command
globals()['Coordinates'] = Coordinates
globals()['Resources'] = Resources
from space_tycoon_client.model.ships_value import ShipsValue


class TestShipsValue(unittest.TestCase):
    """ShipsValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShipsValue(self):
        """Test ShipsValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ShipsValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
