# coding: utf-8

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import space_tycoon_client
from space_tycoon_client.models.resources import Resources  # noqa: E501
from space_tycoon_client.rest import ApiException


class TestResources(unittest.TestCase):
    """Resources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResources(self):
        """Test Resources"""
        # FIXME: construct object with mandatory attributes with example values
        # model = space_tycoon_client.models.resources.Resources()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
