# coding: utf-8

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import space_tycoon_client
from space_tycoon_client.api.game_api import GameApi  # noqa: E501
from space_tycoon_client.rest import ApiException


class TestGameApi(unittest.TestCase):
    """GameApi unit test stubs"""

    def setUp(self):
        self.api = GameApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_commands_post(self):
        """Test case for commands_post

        Specify commands for your ships  # noqa: E501
        """
        pass

    def test_current_tick_get(self):
        """Test case for current_tick_get

        Returns the current tick, season and the approximate time until the next tick.  # noqa: E501
        """
        pass

    def test_data_get(self):
        """Test case for data_get

        Dynamic game data (scores, prices, spaceship positions)  # noqa: E501
        """
        pass

    def test_end_turn_post(self):
        """Test case for end_turn_post

        Signal that your turn is over for the current tick. Returns the current tick and the approximate time until the next tick.  # noqa: E501
        """
        pass

    def test_login_post(self):
        """Test case for login_post

        Get user session  # noqa: E501
        """
        pass

    def test_logout_get(self):
        """Test case for logout_get

        """
        pass

    def test_reports_get(self):
        """Test case for reports_get

        Fetch statistical data about all players.  # noqa: E501
        """
        pass

    def test_static_data_get(self):
        """Test case for static_data_get

        Data that do not change during entire season, such as ships classes.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
