"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import space_tycoon_client
from space_tycoon_client.model.construct_command_all_of import ConstructCommandAllOf


class TestConstructCommandAllOf(unittest.TestCase):
    """ConstructCommandAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConstructCommandAllOf(self):
        """Test ConstructCommandAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConstructCommandAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
