"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import space_tycoon_client
from space_tycoon_client.model.resource import Resource
from space_tycoon_client.model.trading_resource_all_of import TradingResourceAllOf
globals()['Resource'] = Resource
globals()['TradingResourceAllOf'] = TradingResourceAllOf
from space_tycoon_client.model.trading_resource import TradingResource


class TestTradingResource(unittest.TestCase):
    """TradingResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTradingResource(self):
        """Test TradingResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TradingResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
