"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import space_tycoon_client
from space_tycoon_client.model.combat import Combat
from space_tycoon_client.model.price import Price
from space_tycoon_client.model.profiling import Profiling
from space_tycoon_client.model.score import Score
from space_tycoon_client.model.trade import Trade
globals()['Combat'] = Combat
globals()['Price'] = Price
globals()['Profiling'] = Profiling
globals()['Score'] = Score
globals()['Trade'] = Trade
from space_tycoon_client.model.reports import Reports


class TestReports(unittest.TestCase):
    """Reports unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReports(self):
        """Test Reports"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Reports()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
