"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import space_tycoon_client
from space_tycoon_client.model.command import Command
from space_tycoon_client.model.destination import Destination
from space_tycoon_client.model.move_command_all_of import MoveCommandAllOf
globals()['Command'] = Command
globals()['Destination'] = Destination
globals()['MoveCommandAllOf'] = MoveCommandAllOf
from space_tycoon_client.model.move_command import MoveCommand


class TestMoveCommand(unittest.TestCase):
    """MoveCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMoveCommand(self):
        """Test MoveCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MoveCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
