"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import space_tycoon_client
from space_tycoon_client.model.ships_value import ShipsValue
globals()['ShipsValue'] = ShipsValue
from space_tycoon_client.model.ships import Ships


class TestShips(unittest.TestCase):
    """Ships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShips(self):
        """Test Ships"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Ships()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
