# coding: utf-8

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import space_tycoon_client
from space_tycoon_client.api.logout_api import LogoutApi  # noqa: E501
from space_tycoon_client.rest import ApiException


class TestLogoutApi(unittest.TestCase):
    """LogoutApi unit test stubs"""

    def setUp(self):
        self.api = LogoutApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_logout_get(self):
        """Test case for logout_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
