"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import space_tycoon_client
from space_tycoon_client.api.commands_api import CommandsApi  # noqa: E501


class TestCommandsApi(unittest.TestCase):
    """CommandsApi unit test stubs"""

    def setUp(self):
        self.api = CommandsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_commands_post(self):
        """Test case for commands_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
