"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import space_tycoon_client
from space_tycoon_client.model.command import Command
from space_tycoon_client.model.construct_command_all_of import ConstructCommandAllOf
globals()['Command'] = Command
globals()['ConstructCommandAllOf'] = ConstructCommandAllOf
from space_tycoon_client.model.construct_command import ConstructCommand


class TestConstructCommand(unittest.TestCase):
    """ConstructCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConstructCommand(self):
        """Test ConstructCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConstructCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
