"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import space_tycoon_client
from space_tycoon_client.api.login_api import LoginApi  # noqa: E501


class TestLoginApi(unittest.TestCase):
    """LoginApi unit test stubs"""

    def setUp(self):
        self.api = LoginApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_login_post(self):
        """Test case for login_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
