"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import space_tycoon_client
from space_tycoon_client.model.login_post200_response import LoginPost200Response


class TestLoginPost200Response(unittest.TestCase):
    """LoginPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginPost200Response(self):
        """Test LoginPost200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoginPost200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
