# coding: utf-8

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import space_tycoon_client
from space_tycoon_client.api.data_api import DataApi  # noqa: E501
from space_tycoon_client.rest import ApiException


class TestDataApi(unittest.TestCase):
    """DataApi unit test stubs"""

    def setUp(self):
        self.api = DataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_data_get(self):
        """Test case for data_get

        Dynamic game data (scores, prices, spaceship positions)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
