"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import space_tycoon_client
from space_tycoon_client.model.trading_resource import TradingResource
globals()['TradingResource'] = TradingResource
from space_tycoon_client.model.trading_resources import TradingResources


class TestTradingResources(unittest.TestCase):
    """TradingResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTradingResources(self):
        """Test TradingResources"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TradingResources()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
