# coding: utf-8

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import space_tycoon_client
from space_tycoon_client.api.dev_api import DevApi  # noqa: E501
from space_tycoon_client.rest import ApiException


class TestDevApi(unittest.TestCase):
    """DevApi unit test stubs"""

    def setUp(self):
        self.api = DevApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user_post(self):
        """Test case for create_user_post

        create user  # noqa: E501
        """
        pass

    def test_reset_get(self):
        """Test case for reset_get

        start new season (call this after creating the users)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
