"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import space_tycoon_client
from space_tycoon_client.model.current_tick import CurrentTick
from space_tycoon_client.model.planets import Planets
from space_tycoon_client.model.player_id import PlayerId
from space_tycoon_client.model.players import Players
from space_tycoon_client.model.ships import Ships
globals()['CurrentTick'] = CurrentTick
globals()['Planets'] = Planets
globals()['PlayerId'] = PlayerId
globals()['Players'] = Players
globals()['Ships'] = Ships
from space_tycoon_client.model.data import Data


class TestData(unittest.TestCase):
    """Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testData(self):
        """Test Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
