"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import space_tycoon_client
from space_tycoon_client.model.coordinates import Coordinates
from space_tycoon_client.model.trading_resources import TradingResources
globals()['Coordinates'] = Coordinates
globals()['TradingResources'] = TradingResources
from space_tycoon_client.model.planets_value import PlanetsValue


class TestPlanetsValue(unittest.TestCase):
    """PlanetsValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlanetsValue(self):
        """Test PlanetsValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlanetsValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
