"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import space_tycoon_client
from space_tycoon_client.model.static_data_ship_classes_value import StaticDataShipClassesValue


class TestStaticDataShipClassesValue(unittest.TestCase):
    """StaticDataShipClassesValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStaticDataShipClassesValue(self):
        """Test StaticDataShipClassesValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StaticDataShipClassesValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
