# flake8: noqa

"""
    Space Tycoon

    Space Tycoon server.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from space_tycoon_client.api_client import ApiClient

# import Configuration
from space_tycoon_client.configuration import Configuration

# import exceptions
from space_tycoon_client.exceptions import OpenApiException
from space_tycoon_client.exceptions import ApiAttributeError
from space_tycoon_client.exceptions import ApiTypeError
from space_tycoon_client.exceptions import ApiValueError
from space_tycoon_client.exceptions import ApiKeyError
from space_tycoon_client.exceptions import ApiException
